### ISSUE TITLE
23 hour work cycle

### ISSUE THREAD

**Issue by GRektK** [cheesenibbles123/OliverbotPublic#2]
#### Solution:
Over time, ;work will need to be performed later and later as no one is on at the exact same time every day. If the work cycle is 23 hours, there will be a short grace period so as to still only allow 1 work per day unless you are extremely precise and will cut down on the amount of pushback.

#### Alternatives:
Obviously there the timezone solution, which you have thought through in great detail and I have no need to explain further. Timezones would be bulky to work around with the 9-5 setup and would result in lots of missed work opportunities. 12-12 could result in working twice in a row which I feel is cheesy as it allows someone who is online every other day to get the same profits as someone who is on every day. I've considered other work cycle periods, however the shorter it is the easier it is to cheese out additional work. 20 hours would be the bare minimum, any less and you're practically begging for it to be abused.

#### Additional context:
[My original paragraph outlining the 23 hour work cycle vs timezone based system ](https://discordapp.com/channels/802132410954153994/802141135236890644/814698525060366346)

#### Further reading:
The main inspiration for my idea came from the mobile game Clash Royale. It had a similar issue with one of their features. In that game you could request cards once every 8 hours, for a total of 3 times a day. To get all 3 requests you would have to be online exactly every 8 hours ready to push the button which was impractical and difficult. To solve this, they changed it to 1 request every 7 hours. Still only allowing 3 requests a day, but giving much more of a grace period so you wouldn't have to be on at the exact time to get the intended value. In theory you could get more requests over time, but in practice people have to sleep and work and won't be able to cheese it very easily.

**Comment by cheesenibbles123** [comment]
Converted to 23hr delay for the time being, we'll see how it holds up. If it goes well it'll remain, otherwise I'll have to look more into the alternative solution I proposed.
