### ISSUE TITLE
Slot machine eats my money

### ISSUE THREAD

**Issue by GRektK** [cheesenibbles123/OliverbotPublic#9]
The slot machine eats my money. 
Make it say profit or I'm going to riot.
There is no form of gambling where you don't initially put something in, then get something out at the end. It makes no sense for the slot machine to take the 5 I put in, then say "income 0," and have that mean it didn't affect my balance. Change it or im going to go off.

**Comment by cheesenibbles123** [comment]
Changed from `income` to `profit` on gamble card.
